### ISSUE TITLE
Version 2.6.2

### ISSUE THREAD

**Issue by DaniellPlasmmer** [po-devs/android-client#174]
- [x] #171 Portuguese language;
- [ ] #172 Chinese language;
- [ ] #173 Japanese language;
- [ ] #175 Hindi language;
- [ ] #59 Double battles not working at all;
- [ ] #4 Allow backup;
- [ ] #42 Export teams to PC version;
- [ ] #15 Externalize resources;
- [ ] #63 Crash after disconnecting/reconnecting [UNSURE];
- [ ] #32 Show lifeorb damage;
- [ ] #36 Fix PMs;
- [ ] #54 Teambuilder shows Sp Attack and Sp Defense instead of Special in the 1st Gen;

**Comment by DaniellPlasmmer** [comment]
?
